all: TCP_iterative_server.o TCP_iterative_client.o

TCP_iterative_client.o: TCP_client.c	
	gcc TCP_client.c -o TCP_iterative_client.o
	
TCP_iterative_server.o: TCP_iterative_server.c
	gcc TCP_iterative_server.c -o TCP_iterative_server.o